new python versions support update
OpenNFT/OpenNFT pull request #84
Opened 2020-10-09 11:38 UTC by TheAmid

CHANGE:

Changed async=True to background=True

CHECK:

Project works with python version up to 3.8.6 and MATLAB 2020b.

2020-10-09 19:41 UTC, espdev commented
@TheAmid What is minimal version of Matlab is supported after these changes?

Also we can drop Python 3.5 support because 3.5 is no longer supported officially.
https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html

We need to specify minimal Python and Matlab versions which we support.

2020-10-09 20:26 UTC, TheAmid commented
The minimal version of Matlab is R2017b with Python 3.6

2020-10-09 22:49 UTC, espdev commented
> 
> 
> The minimal version of Matlab is R2017b with Python 3.6

Have you tested "Matlab is R2017b with Python 3.6" with `background=True` instead of `async=True`?

2020-10-10 13:20 UTC, TheAmid commented
Good question. I have tested Matlab R2017b + Python 3.6 and everything works fine.

2020-10-10 17:18 UTC, espdev approved these changes

2020-10-10 21:00 UTC, espdev commented
@TheAmid Could you change minimal Python version here:
https://github.com/OpenNFT/OpenNFT/blob/master/setup.py#L25

Also you can specify minimal MATLAB version in `setup.py` and check it when installing Matlab engine for Python.

2020-10-11 07:22 UTC, TheAmid commented
I edited supported Python versions and added Vatlab version requirements. 

But I'm not sure it is necessary for Matlab. Its version depends on Python and <R2017b versions won't work with "newest" Python 3.6.

2020-10-11 09:02 UTC, espdev commented on setup.py
> +    matlab_requires=MATLAB_REQUIRES,
It doesn't work that way. You need to implement Matlab check version in code where we find and install matlab engine Python package.

Somewhere in this function:

https://github.com/OpenNFT/OpenNFT/blob/e8caef4a8020b46aaeb28d06166aa7e634e3bc69/setup.py#L83

2020-10-11 09:03 UTC, espdev requested changes
Implement correct check of Matlab version.

2020-10-11 19:32 UTC, espdev approved these changes

2020-10-13 17:22 UTC, ykoush commented
closes #76

2020-10-13 17:34 UTC, merged